print("Bad at math? You can calculate your next tip here!")
bill = input("What was the total bill? $")
tip_percent = input("How much tip would you like to give? 10, 12, or 15? ")
split = input("How many people to split the bill among? ")
final_amount = round(((float(bill) + (float(bill) * (float(tip_percent)/100.0))) / float(split)), 2)
print(f'Each person should pay: ${final_amount}')